spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration   # 特別排除 DevTools 的資料庫配置
  sever:
    port: 8088
  security:
    user:
      name: admin       # 自定义用户名
      password: 123456  # 自定义密码